import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const CACHE_BUST = "v2"; // Increment when updating the image

export const metadata: Metadata = {
    title: "GitDocify",
    description: "Generated by Binidu Ranasinghe",
    icons: {
        icon: "/favicon.ico",
    },
    openGraph: {
        title: "GitDocify",
        description: "Generated by Binidu Ranasinghe",
        url: "https://readme-generator-gray.vercel.app",
        siteName: "GitDocify",
        images: [
            {
                url: `https://readme-generator-gray.vercel.app/image_preview.png?${CACHE_BUST}`,
                width: 1200,
                height: 630,
            },
        ],
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: "GitDocify",
        description: "Generated by Binidu Ranasinghe",
        images: [`https://readme-generator-gray.vercel.app/image_preview.png?${CACHE_BUST}`],
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}
